fix: get_instructors function
frappe/lms pull request #572
Opened 2023-07-27 09:14 UTC by tahir-zaqout

instructors = frappe.get_all(
		"Course Instructor", {"parent": course}, ["instructor"], order_by="idx", pluck=""
	)
it return like
	[
		{"instructor": "user1"},
		{"instructor": "user2"}
	]
and the
if not instructors:
    instructors = frappe.db.get_value("LMS Course", course, "owner").split(" ")

return ["user1", "user2"]

and it make error if get all return []
because instructor.instructor at  https://github.com/frappe/lms/blob/main/lms/lms/utils.py#L167

2023-07-27 13:33 UTC, ahmadRagheb commented
Great Job @tahir-zaqout

2023-08-06 11:46 UTC, tahirAnvil commented
@pateljannat

2023-08-08 07:15 UTC, tahir-zaqout commented
@pateljannat

2023-08-10 09:57 UTC, niraj2477 commented on lms/lms/utils.py
> +		"Course Instructor", {"parent": course}, ["instructor"], order_by="idx", pluck="instructor"
No of pluck here. Below change would do

2023-08-10 09:59 UTC, niraj2477 commented
This PR will fix : https://github.com/frappe/lms/issues/587

2023-08-25 11:59 UTC, pateljannat requested changes

2023-08-25 11:59 UTC, pateljannat commented on lms/lms/utils.py
> +		"Course Instructor", {"parent": course}, ["instructor"], order_by="idx", pluck="instructor"
@tahir-zaqout no need to have a fields array when you are plucking.

2023-08-25 12:03 UTC, pateljannat commented on lms/lms/utils.py
> +		"Course Instructor", {"parent": course}, ["instructor"], order_by="idx", pluck="instructor"
Also please install pre-commit on your system. It will fix the linters before committing.

2023-08-25 12:33 UTC, merged