Allow to Set Different Certificate Print Format for each LMS Course
frappe/lms pull request #574
Opened 2023-07-29 11:26 UTC by Rola-anvil

This is to allow the system to create different certificates for each course

2023-07-30 19:18 UTC, ahmadRagheb commented
nice job rola

2023-07-31 04:08 UTC, pateljannat commented
@Rola-anvil I don't understand the need for a link field in the LMS Course doctype.

When creating a certificate, it considers the default print format set.

You can just make your desired format as default.

2023-08-02 09:10 UTC, Rola-anvil commented
But Every course needs a different certificate design, so I have created this field to let the system user choose a custom certificate design or  consider the default one

2023-10-25 06:31 UTC, pateljannat requested changes

2023-10-25 06:31 UTC, pateljannat commented on lms/fixtures/custom_field.json
> +    "dt": "LMS Course",
@Rola-anvil why add a custom field in LMS Course doctype when you can add a standard field.

2023-10-25 07:38 UTC, pateljannat commented on lms/fixtures/custom_field.json
> +    "dt": "LMS Course",
Also, you have made the changes in the main branch of your fork. Can you create another branch for this feature instead?

2024-05-02 14:22 UTC, closed without merging