Added batch start and end date validation
frappe/lms pull request #711
Opened 2023-12-23 18:37 UTC by ph4ni

2023-12-26 04:32 UTC, pateljannat commented
@ph4ni please add a description

2023-12-26 04:35 UTC, pateljannat requested changes

2023-12-26 04:35 UTC, pateljannat commented on lms/lms/doctype/lms_batch/lms_batch.py
> +		self.validate_batch_end_date():
Remove the colon at the end

2023-12-26 04:35 UTC, pateljannat commented on lms/lms/doctype/lms_batch/lms_batch.py
> +		if(self.end_date<self.start_date):
Add space beside the operator.

2023-12-26 04:35 UTC, pateljannat commented on lms/lms/doctype/lms_batch/lms_batch.py
> +			frappe.throw("Batch end date cannot be before the batch start date")
Make this string translatable.

2023-12-27 06:03 UTC, ph4ni commented
done

2024-05-24 09:49 UTC, merged