fix: show "Seats Left" instead of "Seat Left" if more than 1 seat is available
frappe/lms pull request #877
Opened 2024-06-14 11:02 UTC by nikkothari22

Kinda pointless PR but meh 🤷🏻 - it was irking me.

PS: Not sure if this is the right way to do it since the code (especially the styles) are duplicated in the two badges.

2024-06-21 04:52 UTC, pateljannat requested changes

2024-06-21 04:52 UTC, pateljannat commented on frontend/src/components/BatchCard.vue
> +			{{ batch.seats_left }} {{ __('Seats Left') }}
Maybe try with 2 spans here instead of two badges.

2024-06-24 09:05 UTC, merged

2024-06-25 15:53 UTC, NagariaHussain commented
![CleanShot 2024-06-25 at 21 23 29@2x](https://github.com/frappe/lms/assets/34810212/5bed26a4-fce5-4821-9929-2147ba01acb4)

😅

2024-06-25 15:55 UTC, NagariaHussain commented on frontend/src/components/BatchOverlay.vue
> +			{{ seats_left }} <span v-if="batch.seats_left > 1">{{ __('Seats Left') }}</span><span v-else-if="batch.seats_left == 1">{{ __('Seat Left') }}</span>
Should have been just `seats_left` and not `batch.seats_left`